### ISSUE TITLE
Incorrect component for menu without icon

### ISSUE THREAD

**Issue by tylim88** [creativetimofficial/ct-blk-design-system-pro-react#2]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
menu without icon should not look the same with menu with icon

# Current Behavior
![img1](https://user-images.githubusercontent.com/5227509/59157855-8d575c00-8ae4-11e9-98fc-e510486b3d51.png)
they look the same

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello there, @tylim88 ,

Thank you for your interest in working with our products.
Here is the code for the Menu without icons:
```
<Navbar className="bg-primary" expand="lg">
    <Container>
      <NavbarBrand href="#pablo" onClick={e => e.preventDefault()}>
        Menu
      </NavbarBrand>
      <button className="navbar-toggler" aria-expanded={false}>
        <span className="navbar-toggler-bar bar1" />
        <span className="navbar-toggler-bar bar2" />
        <span className="navbar-toggler-bar bar3" />
      </button>
      <Collapse navbar isOpen={false}>
        <Nav navbar>
          <NavItem className="active">
            <NavLink
              href="#pablo"
              onClick={e => e.preventDefault()}
            >
              <p>Link</p>
            </NavLink>
          </NavItem>
          <NavItem>
            <NavLink
              href="#pablo"
              onClick={e => e.preventDefault()}
            >
              <p>Link</p>
            </NavLink>
          </NavItem>
          <UncontrolledDropdown nav>
            <DropdownToggle
              aria-expanded={false}
              aria-haspopup={true}
              caret
              color="default"
              data-toggle="dropdown"
              href="http://example.com"
              id="navbarDropdownMenuLink"
              nav
            >
              <p>Dropdown</p>
            </DropdownToggle>
            <DropdownMenu aria-labelledby="navbarDropdownMenuLink">
              <DropdownItem
                href="#pablo"
                onClick={e => e.preventDefault()}
              >
                Action
              </DropdownItem>
              <DropdownItem
                href="#pablo"
                onClick={e => e.preventDefault()}
              >
                Another action
              </DropdownItem>
              <DropdownItem
                href="#pablo"
                onClick={e => e.preventDefault()}
              >
                Something else here
              </DropdownItem>
            </DropdownMenu>
          </UncontrolledDropdown>
        </Nav>
      </Collapse>
    </Container>
  </Navbar>
```

Best, 
Manu

**Comment by tylim88** [comment]
thank you @EINazare
