### ISSUE TITLE
Icon is not properly placed

### ISSUE THREAD

**Issue by tylim88** [creativetimofficial/ct-blk-design-system-pro-react#3]
!!! IF YOU DO NOT USE THIS ISSUES TEAMPLATE, YOUR ISSUE IS LIABLE TO BEING IGNORED BY US

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

icon should stay in the circle

# Current Behavior

![img1](https://user-images.githubusercontent.com/5227509/59157869-f343e380-8ae4-11e9-8bec-8723b0d5d715.png)
icon escaping the border

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device:
* Operating System:
* Browser and Version:

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by einazare** [comment]
Hello again, @tylim88 ,

This is actually our design.
The icons are displayed as they should be.

Best,
Manu
