### ISSUE TITLE
[Bug] Collapsed navbar displaying scrollbars

### ISSUE THREAD

**Issue by UmungoBungo** [creativetimofficial/ct-blk-design-system-pro-react#4]
### Version
1.0.0
### Reproduction link
https://github.com/creativetimofficial/ct-blk-design-system-pro-react
### Operating System
Windows
### Device
PC
### Browser & Version
Chrome and Edge
### Steps to reproduce
Shrink the window so that the hamburger icon shows up in the navbar.
Expand the navbar.
### What is expected?
There should be no scroll bars, it should just be a box with rounded edges. This is displaying correctly on the live preview of the **free** version of BLK Design System.
### What is actually happening?
When expanding the navbar, scroll bars appear.

---
### Additional comments
![image](https://user-images.githubusercontent.com/22192773/62003558-619f3c80-b14b-11e9-98de-219110f3987d.png)

**Comment by einazare** [comment]
Hello there, @UmungoBungo ,

Thank you for your interest in working with our products.
The vertical scrollbar should be there, but the horizontal one should not appear.
To solve this issue, add the following css in your styles:
```
.navbar .navbar-collapse.collapse, .navbar .navbar-collapse.collapsing{
    overflow-x: hidden;
}
```

Best,
Manu

**Comment by UmungoBungo** [comment]
Thanks Manu,

I don't see why there should be a vertical scrollbar... so I ammended it to this:

```
.navbar .navbar-collapse.collapse, .navbar .navbar-collapse.collapsing{
    overflow-x: hidden;
    overflow-y: hidden;
}
```

I appreciate your fast response

**Comment by einazare** [comment]
Hello again, @UmungoBungo ,

The vertical scrollbar should be there when you have for example, 10 links inside the collapse, instead of 3 dropdowns. The last 3-5 links on small phones will not be visible, so a scroll should be there, so you can scroll down inside the collapse and be able to navigate to all 10 links. 
Hope this clarifies your question.
Also, please leave the issue opened so we do not forget on our next update to add the above fix in our product as well.

Best,
Manu

**Comment by UmungoBungo** [comment]
Hey Manu, yes I agree that there should be vertical scroll bar when there are items that are hidden. However, in this particular case it is not functioning correctly. In my screenshot, there is nothing to scroll to, as the drowdowns are collapsed. Even when you expand these dropdowns, it looks like this:
![Blk_Issue](https://user-images.githubusercontent.com/22192773/62407269-01474980-b5e8-11e9-8a24-494eee8c248a.png)

As you can see, the vertical scrollbar is visible, but greyed out as there is nowhere to scroll.

**Comment by einazare** [comment]
Hello again, @UmungoBungo ,

Please add the following code inside your css:
```
.navbar .navbar-collapse.collapse{
  max-height: 300px;
}
```

Best,
Manu
