### ISSUE TITLE
[Bug] btn-icon Class flashing when mouse-over higher components

### ISSUE THREAD

**Issue by UmungoBungo** [creativetimofficial/ct-blk-design-system-pro-react#5]
### Version
1.0.0
### Reproduction link
https://demos.creative-tim.com/blk-design-system-pro-react/#/documentation/buttons
### Operating System
Windows
### Device
PC
### Browser & Version
Chrome
### Steps to reproduce
Mouse-over on buttons that are displayed earlier.
Notice the buttons below flash as if they have also had a mouse-over event.
Buttons before this are unaffected.
### What is expected?
Only the button that has the mouse go over it should flash.
### What is actually happening?
Mouse-over on buttons that are displayed earlier.
Notice the buttons below flash as if they have also had a mouse-over event.
Buttons before this are unaffected.

---
### Additional comments
This only occurs in Chrome and Brave (built on Chromium). This does not occur in Edge or Firefox.

Here is a video of it occuring, pay attention to 'Pint it - 212'
![ezgif-4-81a09e55c0bc](https://user-images.githubusercontent.com/22192773/62407651-656d0c00-b5ee-11e9-9efe-dd890b8ca820.gif)

**Comment by einazare** [comment]
Hello there, @UmungoBungo ,

I've hovered around the buttons.
The issue you are describing is not happening.
Could you please give us your Browser version?

Best,
Manu

**Comment by UmungoBungo** [comment]
The Chrome versions is:
Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by einazare** [comment]
Hello again, @UmungoBungo ,

I've checked again on another windows machine.
It seems that the issue is happening from some of our dependencies from the documentation.
If you check here: https://demos.creative-tim.com/blk-design-system-pro-react/#/index
The issue is not happening.
I will investigate further to see why this is happening.

Best,
Manu

**Comment by UmungoBungo** [comment]
I think it may have something to do with the ID perhaps? I notced that on the index page, they are all individually coded instances.

In my application, I have them genereated as a a result of a map:
```
pledges.map(pledge => (
                <Media>
                    <a
                        className="pull-left"
                        href={'https://open.spotify.com/embed/track/' + pledge.spotifyID}
                        target="_blank"
                        rel="noopener noreferrer">
                        <i className="tim-icons icon-triangle-right-17 text-success" />
                    </a>
                    <Media body>
                        <Media heading tag="h5">
                            {pledge.track}
                            <small className="text-muted"> - {" "}{pledge.artist}</small>
                        </Media>
                        <div className="media-footer">
                            <Button
                                className="btn-simple"
                                color="info"
                                size="sm">
                                ${pledge.pledged}; Accepted {" "} {Moment().diff(Moment.unix(pledge.date_claimed.seconds), 'days')}{" "} day(s) ago
                            </Button>
                        </div>
                    </Media>
                </Media>
            )
```

And I'm thinking that the Buttons need their own IDs perhaps? I don't have access to the source code for the documentation where it is also occuring, so I can't check that theory.

**Comment by einazare** [comment]
Hello again, @UmungoBungo ,

They have no ID's on them :(.
It's strange that on Mac Chrome the issue doesn't exist, but on Windows Chrome the issue exists.
I mean there is not JavaScript for the hover effects, it's only CSS.
That's why I am not sure why the issue exists and how to solve it.

Best,
Manu
