### ISSUE TITLE
[Bug] Card title on Register  page is not respecting responsive

### ISSUE THREAD

**Issue by betthrone-auto** [creativetimofficial/ct-blk-design-system-pro-react#7]
### Version
1.1.0
### Reproduction link
http://non
### Operating System
IOS
### Device
IphoneX
### Browser & Version
Chrome 84
### Steps to reproduce
1.Open register page in mobile 
2.look at the card header (Register)
3.it goes out of background picture
### What is expected?
it should remain in background picture border
### What is actually happening?
it goes out of background picture

---

**Comment by einazare** [comment]
Hello there, @betthrone-auto ,

We've checked the issue, and it seems that the title sits ok.
Could you please share with us an image of the issue?

Best,
Manu

**Comment by Pooriafd** [comment]
![Screenshot_20200818-192638_Chrome](https://user-images.githubusercontent.com/3437857/90545337-ca0ef080-e188-11ea-9c71-8abbf3470426.jpg)
This picture is just taken from your demo website:
https://demos.creative-tim.com/blk-design-system-pro-react/?_ga=2.24666938.186117167.1597771553-1277721791.1596521036#/index

**Comment by einazare** [comment]
Hello again, @Pooriafd ,

That is intended to be like that.
If you wish, you can add the class "text-white" on the `<CardTitle>` element.

Best,
Manu
